version: '3'
services:
  # Database image
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  # # Own code webserver
  # graphql-api:
  #   build: 
  #     context: .
  #   environment: 
  #     - PORT=80
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - mongodb

  # image specifically for seeding the database
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb