version: '3'
services:
  # Database image
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  # Own code webserver
  graphql-api:
    build: 
      context: .
    ports:
      - "5000:5000"
    links:
      - mongodb

  # image specifically for seeding the database
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb